trigger:
    branches:
        include:
            - master
            - ci-*
            - bug-*
            - feature-*

stages:
    - stage: Build

      jobs:
          - job: Build
            pool:
                vmImage: "windows-latest"

            steps:
                - bash: |
                      echo "##vso[build.updatebuildnumber]$(major).$(minor).$(Build.BuildId)"
                  name: SetBuildName

                - task: PowerShell@2
                  displayName: "PowerShell Script - update version number in project files"
                  inputs:
                      targetType: filePath
                      arguments: "-version '$(Build.BuildNumber)'"
                      filePath: "./.build/UpdateVersion.ps1"

                # Publish projects to specified folder.
                - task: DotNetCoreCLI@2
                  displayName: 'dotnet publish'
                  inputs:
                    command: 'publish'
                    projects: '**/CopyWords.WPF.csproj'
                    arguments: '-o $(Build.ArtifactStagingDirectory)'
                    publishWebProjects: false
                    zipAfterPublish: true
                    modifyOutputPath: true

                # - task: DotNetCoreCLI@2
                #   displayName: "Run unit tests"
                #   inputs:
                #     command: "test"
                #     configuration: "$(BuildConfiguration)"

                - task: PublishBuildArtifacts@1
                  displayName: "Publish Artifact: drop"
                  inputs:
                      PathtoPublish: "$(build.artifactstagingdirectory)"

    - template: /.azuredevops/templates/stages-sync-with-github.yaml
      parameters:
          repository: CopyWords
