trigger: none

pool:
    vmImage: "windows-latest"

steps:
    # - powershell: |
    #     Write-Host "Branch policy"

    - task: DotNetCoreCLI@2
      displayName: "Build solution"
      inputs:
          command: "build"
          configuration: "$(BuildConfiguration)"

    # - task: DotNetCoreCLI@2
    #   displayName: "Run unit tests"
    #   inputs:
    #       command: "test"
    #       configuration: "$(BuildConfiguration)"
